# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TalepWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TalepWindow(object):
    def setupUi(self, TalepWindow):
        TalepWindow.setObjectName("TalepWindow")
        TalepWindow.resize(366, 319)
        self.centralwidget = QtWidgets.QWidget(TalepWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.isimtxt = QtWidgets.QTextEdit(self.centralwidget)
        self.isimtxt.setGeometry(QtCore.QRect(130, 30, 231, 31))
        self.isimtxt.setObjectName("isimtxt")
        self.soyisimtxt = QtWidgets.QTextEdit(self.centralwidget)
        self.soyisimtxt.setGeometry(QtCore.QRect(130, 80, 231, 31))
        self.soyisimtxt.setObjectName("soyisimtxt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 140, 93, 28))
        self.pushButton.setObjectName("pushButton")
        TalepWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TalepWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 26))
        self.menubar.setObjectName("menubar")
        TalepWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TalepWindow)
        self.statusbar.setObjectName("statusbar")
        TalepWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TalepWindow)
        QtCore.QMetaObject.connectSlotsByName(TalepWindow)

    def retranslateUi(self, TalepWindow):
        _translate = QtCore.QCoreApplication.translate
        TalepWindow.setWindowTitle(_translate("TalepWindow", "MainWindow"))
        self.label.setText(_translate("TalepWindow", "İsim"))
        self.label_2.setText(_translate("TalepWindow", "Soyisim"))
        self.pushButton.setText(_translate("TalepWindow", "Gonder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TalepWindow = QtWidgets.QMainWindow()
    ui = Ui_TalepWindow()
    ui.setupUi(TalepWindow)
    TalepWindow.show()
    sys.exit(app.exec_())
